# Generated by Django 3.1.7 on 2022-03-27 23:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agrotoxico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agrotoxico',
            fields=[
                ('idAgrotoxico', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agrotoxico.tipoagrotoxico')),
            ],
        ),
    ]
