# Generated by Django 3.1.7 on 2022-03-29 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cultura', '0001_initial'),
        ('agrotoxico', '0002_agrotoxico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diasCarencia', models.PositiveIntegerField()),
                ('agrotoxico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agrotoxico.agrotoxico')),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cultura.cultura')),
            ],
            options={
                'unique_together': {('cultura', 'agrotoxico')},
            },
        ),
    ]
