name: CI pipeline

on:
  [pull_request, push]

jobs:
  ci-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies for flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with flake8
        run: flake8 . --max-line-length=254 --exclude migrations --show-source --statistics