version: '3'
services:
    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5000:5432
    caderneta_digital:
        build: .
        environment:
            - DJANGO_SETTINGS_MODULE=cadernetaDigital.settings
        volumes:
            - .:/var/www
        ports:
            - 8000:8000
        depends_on:
            - postgres
