# Generated by Django 3.1.7 on 2022-03-28 00:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talhao', '0001_initial'),
        ('cultura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantio',
            fields=[
                ('idPlantio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataPlantio', models.DateField()),
                ('estado', models.CharField(choices=[('Plantado', 'Plantado'), ('Carencia', 'Carencia'), ('Colheita', 'Colheita'), ('Finalizado', 'Finalizado')], max_length=10)),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cultura.cultura')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='talhao.talhao')),
            ],
        ),
    ]
