# Generated by Django 3.1.7 on 2022-03-29 02:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrotoxico', '0002_agrotoxico'),
        ('plantio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociacaoPlantioAgrotoxico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAplicacao', models.DateField()),
                ('dosagemAplicacao', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estadoAnalise', models.CharField(choices=[('S', 'Sucesso'), ('P', 'Com Problema(s)'), ('A', 'Em Análise')], default='A', max_length=1)),
                ('agrotoxico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agrotoxico.agrotoxico')),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plantio.plantio')),
            ],
            options={
                'unique_together': {('plantio', 'agrotoxico', 'dataAplicacao')},
            },
        ),
        migrations.AddField(
            model_name='plantio',
            name='agrotoxico',
            field=models.ManyToManyField(through='plantio.AssociacaoPlantioAgrotoxico', to='agrotoxico.Agrotoxico'),
        ),
    ]
