# Generated by Django 3.1.7 on 2022-03-30 02:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agrotoxico', '0002_agrotoxico'),
        ('plantio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacaoAgrotoxico',
            fields=[
                ('idAplicacao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataAplicacao', models.DateField()),
                ('dosagemAplicacao', models.DecimalField(decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estadoAnalise', models.CharField(choices=[('S', 'Sucesso'), ('P', 'Com Problema(s)'), ('A', 'Em Análise')], default='A', max_length=1)),
                ('agrotoxico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agrotoxico.agrotoxico')),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plantio.plantio')),
            ],
        ),
    ]
