# Generated by Django 3.1.14 on 2022-04-01 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrotoxico', '0002_agrotoxico'),
        ('cultura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diasCarencia', models.PositiveIntegerField()),
                ('agrotoxico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agrotoxico.agrotoxico')),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cultura.cultura')),
            ],
            options={
                'unique_together': {('cultura', 'agrotoxico')},
            },
        ),
        migrations.AddField(
            model_name='cultura',
            name='agrotoxicos',
            field=models.ManyToManyField(through='cultura.Espera', to='agrotoxico.Agrotoxico'),
        ),
    ]
