# Generated by Django 3.1.14 on 2022-04-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultura', '0002_auto_20220401_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultura',
            name='foto',
            field=models.ImageField(max_length=255, null=True, upload_to=''),
        ),
    ]
