# Generated by Django 3.1.7 on 2022-03-23 19:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propriedade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('idTalhao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField()),
                ('idPropriedade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='propriedade.propriedade')),
            ],
            options={
                'unique_together': {('idPropriedade', 'numero')},
            },
        ),
    ]
